### ISSUE TITLE
Use create-react-app to initialise the react project

### ISSUE THREAD

**Issue by agnivabasak** [maulikbahri/Movie-Search-Application#1]
-> Do this in the main branch
-> Refer this : https://reactjs.org/docs/create-a-new-react-app.html

**Comment by ARCHISA26022002** [comment]
Initialized the project using create-react-app 
https://github.com/maulikbahri/Movie-Search-Application/pull/3/commits/a6c01c5b1d036c2c88180a2288351e9caf458a38
